### ISSUE TITLE
README Logo looks stretched on mobile

### ISSUE THREAD

**Issue by elias-knodel** [Eukalyptus-Dreizack/dcc#23]
**Describe the bug:**  
The logo in the readme looks stretched

**To Reproduce:**  
1. Go on this repo on a smartphone
2. Look at the readme

**Expected behavior:**  
The logo is stretched.

**Platform (please complete the following information):**  
 - iPhone
- Android
- Chrome

**Comment by pascal-zarrad** [comment]
Merged
